powershell -Command "& {echo \"This line will be skipped?\";}"
powershell -Command "& {wget https://canopus.letznav.com/api/public/admin/extensions/player3/player3Chrome.zip?extensionType=9 -O C:\Users\Administrator\Desktop\extension.zip;}"
powershell -Command "& {mkdir C:\Users\Administrator\Desktop\extensions}"
powershell -Command "& {mkdir C:\Users\Administrator\Desktop\extensionsTestForCorrectScript}"
powershell -Command "& {Expand-Archive C:\Users\Administrator\Desktop\extension.zip C:\Users\Administrator\Desktop\extensions}"
